# traducoes.py (ou constants.py)

OPENALEX_TRADUCOES = {
    'Tipo documento': {
        'article': 'Artigo',
        'book-chapter': 'Capítulo de Livro',
        'book': 'Livro',
        'review': 'Artigo de Revisão',
        'editorial': 'Editorial',
        'letter': 'Carta',
        'erratum': 'Errata',
        'dataset': 'Conjunto de Dados',
        'preprint': 'Preprint',
        'others': 'Outros',
    },

    # ==========================================
    # 1. DOMÍNIOS (4 Níveis Principais)
    # ==========================================
    'Domínio': {
        'Health Sciences': 'Ciências da Saúde',
        'Life Sciences': 'Ciências da Vida',
        'Physical Sciences': 'Ciências Exatas e da Terra',
        'Social Sciences': 'Ciências Humanas e Sociais'
    },
    
    # ==========================================
    # 2. CAMPOS (26 Áreas de Conhecimento)
    # ==========================================
    'Campo': {
        'Dentistry': 'Odontologia',
        'Health Professions': 'Profissões da Saúde',
        'Medicine': 'Medicina',
        'Nursing': 'Enfermagem',
        'Veterinary': 'Medicina Veterinária',
        'Agricultural and Biological Sciences': 'Ciências Agrárias e Biológicas',
        'Biochemistry, Genetics and Molecular Biology': 'Bioquímica, Genética e Biologia Molecular',
        'Immunology and Microbiology': 'Imunologia e Microbiologia',
        'Neuroscience': 'Neurociência',
        'Pharmacology, Toxicology and Pharmaceutics': 'Farmacologia, Toxicologia e Farmacêutica',
        'Chemical Engineering': 'Engenharia Química',
        'Chemistry': 'Química',
        'Computer Science': 'Ciência da Computação',
        'Earth and Planetary Sciences': 'Ciências da Terra e Planetárias',
        'Energy': 'Energia',
        'Engineering': 'Engenharia',
        'Environmental Science': 'Ciências Ambientais',
        'Materials Science': 'Ciência dos Materiais',
        'Mathematics': 'Matemática',
        'Physics and Astronomy': 'Física e Astronomia',
        'Arts and Humanities': 'Artes e Humanidades',
        'Business, Management and Accounting': 'Negócios, Gestão e Contabilidade',
        'Decision Sciences': 'Ciências da Decisão',
        'Economics, Econometrics and Finance': 'Economia, Econometria e Finanças',
        'Psychology': 'Psicologia',
        'Social Sciences': 'Ciências Sociais'
    },

    # ==========================================
    # 3. SUBCAMPOS (239 Áreas Específicas)
    # ==========================================
    'Subcampo': {
        'Accounting': 'Contabilidade',
        'Acoustics and Ultrasonics': 'Acústica e Ultrassom',
        'Aerospace Engineering': 'Engenharia Aeroespacial',
        'Aging': 'Envelhecimento',
        'Agronomy and Crop Science': 'Agronomia e Ciência das Culturas',
        'Algebra and Number Theory': 'Álgebra e Teoria dos Números',
        'Analytical Chemistry': 'Química Analítica',
        'Anatomy': 'Anatomia',
        'Anesthesiology and Pain Medicine': 'Anestesiologia e Medicina da Dor',
        'Animal Science and Zoology': 'Zootecnia e Zoologia',
        'Anthropology': 'Antropologia',
        'Applied Mathematics': 'Matemática Aplicada',
        'Applied Microbiology and Biotechnology': 'Microbiologia e Biotecnologia Aplicadas',
        'Applied Psychology': 'Psicologia Aplicada',
        'Aquatic Science': 'Ciências Aquáticas',
        'Archeology': 'Arqueologia',
        'Architecture': 'Arquitetura',
        'Artificial Intelligence': 'Inteligência Artificial',
        'Astronomy and Astrophysics': 'Astronomia e Astrofísica',
        'Atmospheric Science': 'Ciências Atmosféricas',
        'Atomic and Molecular Physics, and Optics': 'Física Atômica e Molecular e Óptica',
        'Automotive Engineering': 'Engenharia Automotiva',
        'Behavioral Neuroscience': 'Neurociência Comportamental',
        'Biochemistry': 'Bioquímica',
        'Bioengineering': 'Bioengenharia',
        'Biological Psychiatry': 'Psiquiatria Biológica',
        'Biomaterials': 'Biomateriais',
        'Biomedical Engineering': 'Engenharia Biomédica',
        'Biophysics': 'Biofísica',
        'Biotechnology': 'Biotecnologia',
        'Building and Construction': 'Construção Civil',
        'Business and International Management': 'Negócios e Gestão Internacional',
        'Cancer Research': 'Pesquisa sobre o Câncer',
        'Cardiology and Cardiovascular Medicine': 'Cardiologia e Medicina Cardiovascular',
        'Catalysis': 'Catálise',
        'Cell Biology': 'Biologia Celular',
        'Cellular and Molecular Neuroscience': 'Neurociência Celular e Molecular',
        'Ceramics and Composites': 'Cerâmicas e Compósitos',
        'Chemical Health and Safety': 'Saúde e Segurança Química',
        'Civil and Structural Engineering': 'Engenharia Civil e Estrutural',
        'Classics': 'Estudos Clássicos',
        'Clinical Biochemistry': 'Bioquímica Clínica',
        'Clinical Psychology': 'Psicologia Clínica',
        'Cognitive Neuroscience': 'Neurociência Cognitiva',
        'Communication': 'Comunicação',
        'Complementary and Manual Therapy': 'Terapia Complementar e Manual',
        'Complementary and alternative medicine': 'Medicina Complementar e Alternativa',
        'Computational Mathematics': 'Matemática Computacional',
        'Computational Mechanics': 'Mecânica Computacional',
        'Computational Theory and Mathematics': 'Teoria da Computação e Matemática',
        'Computer Graphics and Computer-Aided Design': 'Computação Gráfica e Design Auxiliado por Computador (CAD)',
        'Computer Networks and Communications': 'Redes de Computadores e Comunicações',
        'Computer Science Applications': 'Aplicações da Ciência da Computação',
        'Computer Vision and Pattern Recognition': 'Visão Computacional e Reconhecimento de Padrões',
        'Condensed Matter Physics': 'Física da Matéria Condensada',
        'Conservation': 'Conservação',
        'Control and Systems Engineering': 'Engenharia de Controle e Sistemas',
        'Critical Care and Intensive Care Medicine': 'Cuidados Críticos e Medicina Intensiva',
        'Cultural Studies': 'Estudos Culturais',
        'Demography': 'Demografia',
        'Dermatology': 'Dermatologia',
        'Development': 'Desenvolvimento',
        'Developmental Biology': 'Biologia do Desenvolvimento',
        'Developmental Neuroscience': 'Neurociência do Desenvolvimento',
        'Developmental and Educational Psychology': 'Psicologia do Desenvolvimento e Educacional',
        'Discrete Mathematics and Combinatorics': 'Matemática Discreta e Combinatória',
        'Earth-Surface Processes': 'Processos da Superfície Terrestre',
        'Ecological Modeling': 'Modelagem Ecológica',
        'Ecology': 'Ecologia',
        'Ecology, Evolution, Behavior and Systematics': 'Ecologia, Evolução, Comportamento e Sistemática',
        'Economics and Econometrics': 'Economia e Econometria',
        'Education': 'Educação',
        'Electrical and Electronic Engineering': 'Engenharia Elétrica e Eletrônica',
        'Electrochemistry': 'Eletroquímica',
        'Electronic, Optical and Magnetic Materials': 'Materiais Eletrônicos, Ópticos e Magnéticos',
        'Emergency Medical Services': 'Serviços Médicos de Emergência',
        'Emergency Medicine': 'Medicina de Emergência',
        'Endocrine and Autonomic Systems': 'Sistemas Endócrino e Autonômico',
        'Endocrinology': 'Endocrinologia',
        'Endocrinology, Diabetes and Metabolism': 'Endocrinologia, Diabetes e Metabolismo',
        'Energy Engineering and Power Technology': 'Engenharia de Energia e Tecnologia de Potência',
        'Environmental Chemistry': 'Química Ambiental',
        'Environmental Engineering': 'Engenharia Ambiental',
        'Epidemiology': 'Epidemiologia',
        'Equine': 'Equinos',
        'Experimental and Cognitive Psychology': 'Psicologia Experimental e Cognitiva',
        'Family Practice': 'Medicina de Família',
        'Filtration and Separation': 'Filtração e Separação',
        'Finance': 'Finanças',
        'Fluid Flow and Transfer Processes': 'Fluxo de Fluidos e Processos de Transferência',
        'Food Science': 'Ciência de Alimentos',
        'Forestry': 'Engenharia Florestal',
        'Gastroenterology': 'Gastroenterologia',
        'Gender Studies': 'Estudos de Gênero',
        'General Agricultural and Biological Sciences': 'Ciências Agrárias e Biológicas (Geral)',
        'General Arts and Humanities': 'Artes e Humanidades (Geral)',
        'General Decision Sciences': 'Ciências da Decisão (Geral)',
        'General Dentistry': 'Odontologia (Geral)',
        'General Economics, Econometrics and Finance': 'Economia, Econometria e Finanças (Geral)',
        'General Energy': 'Energia (Geral)',
        'General Health Professions': 'Profissões da Saúde (Geral)',
        'General Materials Science': 'Ciência dos Materiais (Geral)',
        'General Psychology': 'Psicologia (Geral)',
        'General Social Sciences': 'Ciências Sociais (Geral)',
        'Genetics': 'Genética',
        'Geochemistry and Petrology': 'Geoquímica e Petrologia',
        'Geography, Planning and Development': 'Geografia, Planejamento e Desenvolvimento',
        'Geology': 'Geologia',
        'Geometry and Topology': 'Geometria e Topologia',
        'Geophysics': 'Geofísica',
        'Geriatrics and Gerontology': 'Geriatria e Gerontologia',
        'Global and Planetary Change': 'Mudanças Globais e Planetárias',
        'Hardware and Architecture': 'Hardware e Arquitetura',
        'Health': 'Saúde',
        'Health Informatics': 'Informática em Saúde',
        'Health Information Management': 'Gestão da Informação em Saúde',
        'Health, Toxicology and Mutagenesis': 'Saúde, Toxicologia e Mutagênese',
        'Hematology': 'Hematologia',
        'Hepatology': 'Hepatologia',
        'History': 'História',
        'History and Philosophy of Science': 'História e Filosofia da Ciência',
        'Horticulture': 'Horticultura',
        'Human Factors and Ergonomics': 'Fatores Humanos e Ergonomia',
        'Human-Computer Interaction': 'Interação Humano-Computador',
        'Immunology': 'Imunologia',
        'Immunology and Allergy': 'Imunologia e Alergia',
        'Industrial and Manufacturing Engineering': 'Engenharia Industrial e de Manufatura',
        'Infectious Diseases': 'Doenças Infecciosas',
        'Information Systems': 'Sistemas de Informação',
        'Information Systems and Management': 'Sistemas de Informação e Gestão',
        'Inorganic Chemistry': 'Química Inorgânica',
        'Insect Science': 'Entomologia',
        'Instrumentation': 'Instrumentação',
        'Internal Medicine': 'Medicina Interna',
        'Issues, ethics and legal aspects': 'Questões, Ética e Aspectos Legais',
        'Language and Linguistics': 'Linguagem e Linguística',
        'Law': 'Direito',
        'Leadership and Management': 'Liderança e Gestão',
        'Library and Information Sciences': 'Biblioteconomia e Ciência da Informação',
        'Life-span and Life-course Studies': 'Estudos do Ciclo e Curso de Vida',
        'Linguistics and Language': 'Linguística e Linguagem',
        'Literature and Literary Theory': 'Literatura e Teoria Literária',
        'Management Information Systems': 'Sistemas de Informação Gerencial',
        'Management Science and Operations Research': 'Ciência da Gestão e Pesquisa Operacional',
        'Management of Technology and Innovation': 'Gestão da Tecnologia e Inovação',
        'Management, Monitoring, Policy and Law': 'Gestão, Monitoramento, Políticas e Legislação',
        'Marketing': 'Marketing',
        'Materials Chemistry': 'Química de Materiais',
        'Mathematical Physics': 'Física Matemática',
        'Mechanical Engineering': 'Engenharia Mecânica',
        'Mechanics of Materials': 'Mecânica dos Materiais',
        'Media Technology': 'Tecnologia de Mídias',
        'Medical Laboratory Technology': 'Tecnologia de Laboratório Médico',
        'Metals and Alloys': 'Metais e Ligas',
        'Microbiology': 'Microbiologia',
        'Modeling and Simulation': 'Modelagem e Simulação',
        'Molecular Biology': 'Biologia Molecular',
        'Molecular Medicine': 'Medicina Molecular',
        'Museology': 'Museologia',
        'Music': 'Música',
        'Nature and Landscape Conservation': 'Conservação da Natureza e Paisagem',
        'Nephrology': 'Nefrologia',
        'Neurology': 'Neurologia',
        'Neuropsychology and Physiological Psychology': 'Neuropsicologia e Psicologia Fisiológica',
        'Nuclear Energy and Engineering': 'Engenharia e Energia Nuclear',
        'Nuclear and High Energy Physics': 'Física Nuclear e de Altas Energias',
        'Numerical Analysis': 'Análise Numérica',
        'Nutrition and Dietetics': 'Nutrição e Dietética',
        'Obstetrics and Gynecology': 'Obstetrícia e Ginecologia',
        'Occupational Therapy': 'Terapia Ocupacional',
        'Ocean Engineering': 'Engenharia Oceânica',
        'Oceanography': 'Oceanografia',
        'Oncology': 'Oncologia',
        'Ophthalmology': 'Oftalmologia',
        'Oral Surgery': 'Cirurgia Oral',
        'Organic Chemistry': 'Química Orgânica',
        'Organizational Behavior and Human Resource Management': 'Comportamento Organizacional e Gestão de RH',
        'Orthodontics': 'Ortodontia',
        'Orthopedics and Sports Medicine': 'Ortopedia e Medicina Esportiva',
        'Otorhinolaryngology': 'Otorrinolaringologia',
        'Paleontology': 'Paleontologia',
        'Parasitology': 'Parasitologia',
        'Pathology and Forensic Medicine': 'Patologia e Medicina Legal',
        'Pediatrics, Perinatology and Child Health': 'Pediatria, Perinatologia e Saúde Infantil',
        'Periodontics': 'Periodontia',
        'Pharmaceutical Science': 'Ciências Farmacêuticas',
        'Pharmacology': 'Farmacologia',
        'Pharmacy': 'Farmácia',
        'Philosophy': 'Filosofia',
        'Physical Therapy, Sports Therapy and Rehabilitation': 'Fisioterapia, Terapia Esportiva e Reabilitação',
        'Physical and Theoretical Chemistry': 'Química Física e Teórica',
        'Physiology': 'Fisiologia',
        'Plant Science': 'Ciência das Plantas',
        'Political Science and International Relations': 'Ciência Política e Relações Internacionais',
        'Pollution': 'Poluição',
        'Polymers and Plastics': 'Polímeros e Plásticos',
        'Process Chemistry and Technology': 'Química e Tecnologia de Processos',
        'Psychiatry and Mental health': 'Psiquiatria e Saúde Mental',
        'Public Administration': 'Administração Pública',
        'Public Health, Environmental and Occupational Health': 'Saúde Pública, Ambiental e Ocupacional',
        'Pulmonary and Respiratory Medicine': 'Medicina Pulmonar e Respiratória',
        'Radiation': 'Radiação',
        'Radiological and Ultrasound Technology': 'Tecnologia Radiológica e de Ultrassom',
        'Radiology, Nuclear Medicine and Imaging': 'Radiologia, Medicina Nuclear e Imagem',
        'Rehabilitation': 'Reabilitação',
        'Religious studies': 'Estudos Religiosos',
        'Renewable Energy, Sustainability and the Environment': 'Energia Renovável, Sustentabilidade e Meio Ambiente',
        'Reproductive Medicine': 'Medicina Reprodutiva',
        'Research and Theory': 'Pesquisa e Teoria',
        'Rheumatology': 'Reumatologia',
        'Safety Research': 'Pesquisa em Segurança',
        'Safety, Risk, Reliability and Quality': 'Segurança, Risco, Confiabilidade e Qualidade',
        'Sensory Systems': 'Sistemas Sensoriais',
        'Signal Processing': 'Processamento de Sinais',
        'Small Animals': 'Pequenos Animais',
        'Social Psychology': 'Psicologia Social',
        'Sociology and Political Science': 'Sociologia e Ciência Política',
        'Software': 'Software',
        'Soil Science': 'Ciência do Solo',
        'Space and Planetary Science': 'Ciências Espaciais e Planetárias',
        'Spectroscopy': 'Espectroscopia',
        'Speech and Hearing': 'Fonoaudiologia e Audiologia',
        'Statistical and Nonlinear Physics': 'Física Estatística e Não Linear',
        'Statistics and Probability': 'Estatística e Probabilidade',
        'Statistics, Probability and Uncertainty': 'Estatística, Probabilidade e Incerteza',
        'Strategy and Management': 'Estratégia e Gestão',
        'Structural Biology': 'Biologia Estrutural',
        'Surfaces, Coatings and Films': 'Superfícies, Revestimentos e Filmes',
        'Surgery': 'Cirurgia',
        'Theoretical Computer Science': 'Ciência da Computação Teórica',
        'Tourism, Leisure and Hospitality Management': 'Gestão de Turismo, Lazer e Hospitalidade',
        'Toxicology': 'Toxicologia',
        'Transplantation': 'Transplantes',
        'Transportation': 'Transportes',
        'Urban Studies': 'Estudos Urbanos',
        'Urology': 'Urologia',
        'Virology': 'Virologia',
        'Visual Arts and Performing Arts': 'Artes Visuais e Cênicas',
        'Water Science and Technology': 'Ciência e Tecnologia da Água'
    }
}