# Generated by Django 5.2.1 on 2025-05-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=100, unique=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OAStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_issn_l', models.CharField(max_length=50)),
                ('is_oa', models.BooleanField()),
                ('host_organization_id', models.CharField(max_length=100)),
                ('host_organization_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=100, unique=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('subfield_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=100, unique=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('work_title', models.TextField()),
                ('cited_by_count', models.IntegerField()),
                ('is_oa', models.BooleanField()),
                ('referenced_works_count', models.IntegerField()),
                ('indexed_in', models.JSONField()),
                ('oa_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.oastatus')),
                ('primary_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.primarysource')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.worktype')),
                ('pubyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.year')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=100)),
                ('author_position', models.CharField(max_length=20)),
                ('is_corresponding', models.BooleanField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.topic')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.work')),
            ],
        ),
        migrations.CreateModel(
            name='CitedByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_count', models.IntegerField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.work')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.year')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorshipInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.authorship')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('authorship', 'institution'), name='unique_authorship_institution')],
            },
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.UniqueConstraint(fields=('work', 'author_id'), name='unique_work_author'),
        ),
        migrations.AddConstraint(
            model_name='worktopic',
            constraint=models.UniqueConstraint(fields=('work', 'topic'), name='unique_work_topic'),
        ),
        migrations.AddConstraint(
            model_name='citedbyyear',
            constraint=models.UniqueConstraint(fields=('work', 'year'), name='unique_work_year'),
        ),
    ]
