# Generated by Django 5.2.1 on 2025-06-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0002_alter_work_primary_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
