# Generated by Django 5.2.1 on 2025-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0003_alter_work_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarysource',
            name='host_organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='host_organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='is_oa',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='source_issn_l',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='primarysource',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
