# Generated by Django 5.2.1 on 2025-06-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0004_alter_primarysource_host_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
