# Generated by Django 5.2.1 on 2025-06-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0005_alter_work_work_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='indexed_in',
        ),
    ]
