# Generated by Django 5.2.1 on 2025-06-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0006_remove_work_indexed_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='authorship',
            name='unique_work_author',
        ),
        migrations.RemoveField(
            model_name='authorship',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='authorship',
            name='author_position',
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openalex.author'),
        ),
        migrations.AddConstraint(
            model_name='authorship',
            constraint=models.UniqueConstraint(fields=('work', 'author'), name='unique_work_author'),
        ),
    ]
