# Generated by Django 5.2.1 on 2025-06-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0007_author_remove_authorship_unique_work_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openalex.author'),
        ),
    ]
