# Generated by Django 5.2.1 on 2025-06-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0008_alter_authorship_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openalex.author'),
        ),
    ]
