# Generated by Django 5.2.1 on 2025-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0009_alter_authorship_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
