# Generated by Django 5.2.1 on 2025-08-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0010_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
