# Generated by Django 5.2.1 on 2025-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0011_alter_institution_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cited_by_count',
            field=models.IntegerField(db_index=True),
        ),
    ]
