# Generated by Django 5.2.1 on 2025-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0012_alter_work_cited_by_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
