# Generated by Django 5.2.1 on 2025-09-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0013_alter_institution_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
