# Generated by Django 5.2.1 on 2026-06-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0014_alter_year_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'base_manager_name': 'objects'},
        ),
    ]
