# Generated by Django 5.2.1 on 2026-07-07 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0015_alter_work_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='fwci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openalex.authorposition'),
        ),
    ]
