# Generated by Django 5.2.1 on 2025-12-02 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscopoGeografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: ODS_3', max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, help_text='Ex: Saúde e Bem-Estar', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.rankingtipo')),
            ],
            options={
                'unique_together': {('nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='RankingEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('posicao_minima', models.IntegerField()),
                ('posicao_maxima', models.IntegerField()),
                ('escopo_geografico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rankings.escopogeografico')),
                ('ods', models.ForeignKey(blank=True, help_text='Deixe em branco para rankings gerais ou institucionais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.ods')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.ranking')),
            ],
            options={
                'verbose_name': 'Entrada de Ranking',
                'verbose_name_plural': 'Entradas de Ranking',
                'ordering': ['-ano', 'ranking'],
                'unique_together': {('ranking', 'escopo_geografico', 'ods', 'ano')},
            },
        ),
    ]
