# Generated by Django 5.2.1 on 2025-05-20 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('anoId', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('escopoId', models.IntegerField(primary_key=True, serialize=False)),
                ('escopoNome', models.CharField(max_length=100, unique=True)),
                ('escopoNomeCompleto', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('rankingId', models.IntegerField(primary_key=True, serialize=False)),
                ('rankingNome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.FloatField()),
                ('pontuacaoGeral', models.FloatField(null=True)),
                ('anoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.ano')),
                ('escopoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.escopo')),
                ('rankingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.ranking')),
            ],
            options={
                'db_table_comment': 'Resultados dos rankings em um dado escopo e ano',
                'constraints': [models.UniqueConstraint(fields=('rankingId', 'escopoId', 'anoId'), name='unique_resultados_tripla')],
            },
        ),
    ]
