# Generated by Django 5.2.1 on 2025-05-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escopo',
            name='escopoNomeCompleto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.FloatField()),
                ('pontuacaoGeral', models.FloatField(blank=True, null=True)),
                ('anoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.ano')),
                ('escopoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.escopo')),
                ('rankingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.ranking')),
            ],
            options={
                'db_table_comment': 'Resultados dos rankings em um dado escopo e ano',
            },
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.UniqueConstraint(fields=('rankingId', 'escopoId', 'anoId'), name='unique_resultados_tripla'),
        ),
    ]
