# Generated by Django 5.2.1 on 2026-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ods',
            options={'ordering': ['numero'], 'verbose_name': 'ODS', 'verbose_name_plural': 'ODSs'},
        ),
        migrations.AddField(
            model_name='ods',
            name='numero',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
