# Generated by Django 5.2.1 on 2025-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_alter_escopo_escoponomecompleto_resultado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='id',
        ),
        migrations.AddField(
            model_name='resultado',
            name='cursoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
