# Generated by Django 5.2.1 on 2025-05-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_remove_resultado_id_resultado_cursoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='cursoId',
            new_name='resultadoId',
        ),
    ]
