# Generated by Django 5.2.1 on 2025-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_rename_cursoid_resultado_resultadoid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resultado',
            name='unique_resultados_tripla',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='anoId',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='escopoId',
            new_name='escopo',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='rankingId',
            new_name='ranking',
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.UniqueConstraint(fields=('ranking', 'escopo', 'ano'), name='unique_resultados_tripla'),
        ),
    ]
