# Generated by Django 5.2.1 on 2025-06-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_remove_resultado_unique_resultados_tripla_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='resultado',
            table_comment=None,
        ),
    ]
