# Generated by Django 5.2.1 on 2025-06-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEstilo', models.CharField(max_length=30)),
                ('detalheEstilo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSerie', models.CharField(max_length=30)),
                ('dadosSerie', models.JSONField()),
            ],
            options={
                'ordering': ['nomeSerie'],
            },
        ),
        migrations.CreateModel(
            name='TamanhoGrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanhoVertical', models.IntegerField()),
                ('tamanhoHorizontal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicaoNoPainel', models.IntegerField()),
                ('tituloGrafico', models.CharField(max_length=100)),
                ('tituloEixoGrafico', models.CharField(max_length=100)),
                ('estiloGrafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseGraficos.estilografico')),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseGraficos.painel')),
                ('series', models.ManyToManyField(to='baseGraficos.serie')),
                ('tamanhoGrafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseGraficos.tamanhografico')),
            ],
        ),
    ]
