# Generated by Django 5.2.1 on 2025-06-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafico',
            name='series',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
