# Generated by Django 5.2.1 on 2025-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0002_remove_grafico_series_delete_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico',
            name='series',
            field=models.JSONField(default={}),
        ),
    ]
