# Generated by Django 5.2.1 on 2025-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0003_grafico_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafico',
            name='series',
            field=models.JSONField(default=dict),
        ),
    ]
