# Generated by Django 5.2.1 on 2025-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0004_alter_grafico_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafico',
            options={'ordering': ['painel', 'posicaoNoPainel']},
        ),
        migrations.AddField(
            model_name='estilografico',
            name='numeroIdentificador',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grafico',
            name='series',
            field=models.JSONField(default=dict, help_text='use formato de dicionário   --->   {"serie1": {"2010": 25, "2011": 50}}.   Para passar um elemento None pode usar null'),
        ),
    ]
