# Generated by Django 5.2.1 on 2025-06-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0005_alter_grafico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estilografico',
            options={'ordering': ['numeroIdentificador', 'nomeEstilo']},
        ),
        migrations.RemoveField(
            model_name='estilografico',
            name='detalheEstilo',
        ),
    ]
