# Generated by Django 5.2.1 on 2025-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0006_alter_estilografico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilografico',
            name='nomeEstilo',
            field=models.CharField(max_length=100),
        ),
    ]
