# Generated by Django 5.2.1 on 2025-06-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0007_alter_estilografico_nomeestilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafico',
            name='series',
            field=models.JSONField(default=dict, help_text='use formato de dicionário   --->   {"serie1": {"2010": 25, "2011": 50}}.   Para passar um elemento None pode usar null', null=True),
        ),
    ]
