# Generated by Django 5.2.1 on 2025-06-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0009_alter_grafico_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grafico',
            old_name='tituloEixoGrafico',
            new_name='tituloEixoX',
        ),
    ]
