# Generated by Django 5.2.1 on 2025-06-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0010_rename_tituloeixografico_grafico_tituloeixox'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico',
            name='tituloEixoY',
            field=models.CharField(default='', max_length=100),
        ),
    ]
