# Generated by Django 5.2.1 on 2025-06-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0011_grafico_tituloeixoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficoSucupira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painel', models.CharField(max_length=13)),
                ('posicaoNoPainel', models.IntegerField()),
                ('tituloGrafico', models.CharField(max_length=100)),
                ('tituloEixoX', models.CharField(max_length=100)),
                ('tituloEixoY', models.CharField(default='', max_length=100)),
                ('series', models.JSONField(blank=True, default=dict, help_text='use formato de dicionário   --->   {"serie1": {"2010": 25, "2011": 50}}.   Para passar um elemento None pode usar null', null=True)),
                ('estiloGrafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseGraficos.estilografico')),
                ('tamanhoGrafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseGraficos.tamanhografico')),
            ],
            options={
                'ordering': ['painel', 'posicaoNoPainel'],
            },
        ),
    ]
