# Generated by Django 5.2.1 on 2025-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0012_graficosucupira'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSucupira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPrograma', models.CharField(max_length=13)),
                ('momePrograma', models.CharField(max_length=300)),
            ],
        ),
    ]
