# Generated by Django 5.2.1 on 2025-06-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0013_listasucupira'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaSucupira',
        ),
    ]
