# Generated by Django 5.2.1 on 2025-06-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0015_listasucupira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listasucupira',
            old_name='momePrograma',
            new_name='nomePrograma',
        ),
    ]
