# Generated by Django 5.2.1 on 2025-07-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseGraficos', '0016_rename_momeprograma_listasucupira_nomeprograma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listasucupira',
            options={'ordering': ['nomePrograma', 'codPrograma']},
        ),
    ]
