# Generated by Django 5.2.1 on 2025-05-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAvaliacao',
            fields=[
                ('areaAvaliacaoId', models.IntegerField(primary_key=True, serialize=False)),
                ('areaAvaliacaoNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaBasica',
            fields=[
                ('areaBasicaId', models.IntegerField(primary_key=True, serialize=False)),
                ('areaBasicaNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('centroId', models.IntegerField(primary_key=True, serialize=False)),
                ('centroNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('modalidadeId', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidadeNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nivelId', models.IntegerField(primary_key=True, serialize=False)),
                ('nivelNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('redeId', models.IntegerField(primary_key=True, serialize=False)),
                ('redeNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('situacaoId', models.IntegerField(primary_key=True, serialize=False)),
                ('situacaoNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('unidadeId', models.IntegerField(primary_key=True, serialize=False)),
                ('unidadeNome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('conceito', models.IntegerField()),
                ('ativos', models.IntegerField()),
                ('ingressantes', models.IntegerField()),
                ('cancelados', models.IntegerField()),
                ('trancados', models.IntegerField()),
                ('abandonos', models.IntegerField()),
                ('areaAvaliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.areaavaliacao')),
                ('areaBasica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.areabasica')),
                ('centro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.centro')),
                ('modalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.modalidade')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.nivel')),
                ('rede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.rede')),
                ('situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.situacao')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.unidade')),
            ],
        ),
    ]
