# Generated by Django 5.2.1 on 2025-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='conceito',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
