# Generated by Django 5.2.1 on 2025-05-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_alter_programas_codigo_alter_programas_conceito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas',
            old_name='areaAvaliacao',
            new_name='areaAvaliacao_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='areaBasica',
            new_name='areaBasica_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='centro',
            new_name='centro_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='modalidade',
            new_name='modalidade_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='nivel',
            new_name='nivel_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='rede',
            new_name='rede_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='situacao',
            new_name='situacao_id',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='unidade',
            new_name='unidade_id',
        ),
    ]
