# Generated by Django 5.2.1 on 2025-05-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_rename_areaavaliacao_programas_areaavaliacao_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='abandonos',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='areaAvaliacao_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='areaBasica_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='ativos',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='cancelados',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='centro_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='conceito',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='ingressantes',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='modalidade_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='nivel_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='rede_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='situacao_id',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='trancados',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='unidade_id',
        ),
    ]
