# Generated by Django 5.2.1 on 2025-05-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_remove_programas_abandonos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='abandonos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='areaAvaliacaoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.areaavaliacao'),
        ),
        migrations.AddField(
            model_name='programas',
            name='areaBasicaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.areabasica'),
        ),
        migrations.AddField(
            model_name='programas',
            name='ativos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='cancelados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='centroId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.centro'),
        ),
        migrations.AddField(
            model_name='programas',
            name='codigo',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='conceito',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='ingressantes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='modalidadeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.modalidade'),
        ),
        migrations.AddField(
            model_name='programas',
            name='nivelId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.nivel'),
        ),
        migrations.AddField(
            model_name='programas',
            name='redeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.rede'),
        ),
        migrations.AddField(
            model_name='programas',
            name='situacaoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.situacao'),
        ),
        migrations.AddField(
            model_name='programas',
            name='trancados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programas',
            name='unidadeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.unidade'),
        ),
    ]
