# Generated by Django 5.2.1 on 2025-05-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0006_programas_abandonos_programas_areaavaliacaoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas',
            old_name='areaAvaliacaoId',
            new_name='areaAvaliacao',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='areaBasicaId',
            new_name='areaBasica',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='centroId',
            new_name='centro',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='modalidadeId',
            new_name='modalidade',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='nivelId',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='redeId',
            new_name='rede',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='situacaoId',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='programas',
            old_name='unidadeId',
            new_name='unidade',
        ),
    ]
