# Generated by Django 5.2.1 on 2025-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0007_rename_areaavaliacaoid_programas_areaavaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='id',
        ),
        migrations.AddField(
            model_name='programas',
            name='programazId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
