# Generated by Django 5.2.1 on 2025-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0008_remove_programas_id_programas_programazid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas',
            old_name='programazId',
            new_name='programaId',
        ),
    ]
