# Generated by Django 5.2.1 on 2025-05-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0009_rename_programazid_programas_programaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas',
            old_name='programaId',
            new_name='cursoId',
        ),
    ]
