# Generated by Django 5.2.1 on 2025-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0010_rename_programaid_programas_cursoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas',
            name='abandonos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programas',
            name='ativos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programas',
            name='cancelados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programas',
            name='ingressantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programas',
            name='trancados',
            field=models.IntegerField(null=True),
        ),
    ]
