# Generated by Django 5.2.1 on 2025-08-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('ano_valor', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscenteSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_situacao_discente', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteBolsaProdutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cat_bolsa_produtividade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_categoria_docente', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteRegimeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_regime_trabalho', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_tipo_vinculo_docente_ies', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrauCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_grau_curso', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoIdentificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producao_hash', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoTpAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_autor', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAreaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_area_avaliacao', models.IntegerField(unique=True)),
                ('nm_area_avaliacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_area_conhecimento', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaGrandeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_grande_area_conhecimento', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_situacao_programa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa_hash', models.CharField(max_length=128, unique=True)),
                ('ano_nascimento', models.IntegerField(blank=True, null=True)),
                ('pais_nacionalidade', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='sucupira.pessoapais')),
                ('tp_sexo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='sucupira.pessoasexo')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_programa_hash', models.CharField(max_length=128, unique=True)),
                ('nm_programa_ies', models.CharField(max_length=255)),
                ('an_inicio_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_iniciados', to='sucupira.ano')),
                ('area_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='sucupira.programaareaavaliacao')),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='sucupira.programaareaconhecimento')),
                ('grande_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='sucupira.programagrandearea')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.ano')),
                ('autor_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucupira.pessoa')),
                ('categoria_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.docentecategoria')),
                ('nivel_discente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.graucurso')),
                ('producao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.producaoidentificador')),
                ('tp_autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucupira.producaotpautor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.ano')),
                ('bolsa_produtividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.docentebolsaprodutividade')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.docentecategoria')),
                ('regime_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.docenteregimetrabalho')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.docentevinculo')),
                ('grau_titulacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.graucurso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.pessoa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.programa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'pessoa', 'programa'), name='unique_docente_ano_programa')],
            },
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_ingressante', models.BooleanField(default=False)),
                ('qt_mes_titulacao', models.IntegerField(default=0)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.ano')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucupira.discentesituacao')),
                ('grau_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucupira.graucurso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.pessoa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucupira.programa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'pessoa', 'programa', 'grau_academico'), name='unique_discente_ano_programa_grau')],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_inicio_curso', models.IntegerField()),
                ('grau_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='sucupira.graucurso')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='sucupira.programa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('programa', 'grau_curso'), name='unique_programa_grau')],
            },
        ),
        migrations.CreateModel(
            name='AnoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_conceito_programa', models.CharField(max_length=5)),
                ('in_rede', models.BooleanField(default=False)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_avaliados', to='sucupira.ano')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_anuais', to='sucupira.programa')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_no_ano', to='sucupira.programasituacao')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'programa'), name='unique_ano_programa')],
            },
        ),
    ]
