# Generated by Django 5.2.1 on 2026-07-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrienio',
            fields=[
                ('ds_quadrienio', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='programaconceito',
            name='cd_conceito_programa_original',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='ano',
            name='quadrienio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anos', to='sucupira.quadrienio'),
        ),
    ]
