# Generated by Django 5.2.1 on 2025-08-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producao',
            old_name='producao_id',
            new_name='producao',
        ),
    ]
