# Generated by Django 5.2.1 on 2026-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0002_quadrienio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadrienio',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='quadrienio',
            name='ordem',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
