# Generated by Django 5.2.1 on 2025-08-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0002_rename_producao_id_producao_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='an_inicio_programa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
