# Generated by Django 5.2.1 on 2025-09-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0003_alter_programa_an_inicio_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_faixa_etaria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='discente',
            name='faixa_etaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.faixaetaria'),
        ),
        migrations.AddField(
            model_name='docente',
            name='faixa_etaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sucupira.faixaetaria'),
        ),
    ]
