# Generated by Django 5.2.1 on 2026-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0003_alter_quadrienio_options_quadrienio_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadrienio',
            name='ordem',
            field=models.IntegerField(unique=True),
        ),
    ]
