# Generated by Django 5.2.1 on 2025-09-05 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0004_faixaetaria_discente_faixa_etaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaTipoNacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_tipo_nacionalidade', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_nacionalidade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='sucupira.pessoatiponacionalidade'),
        ),
    ]
