# Generated by Django 5.2.1 on 2026-07-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucupira', '0004_alter_quadrienio_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaconceito',
            options={'ordering': ['cd_conceito_programa']},
        ),
    ]
