name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12, 3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install System Dependencies 
      run: |
        sudo apt-get update
        # Add your compilation dependencies here
        sudo apt-get install -y \
          libpq-dev \             
          libmysqlclient-dev \    
          libjpeg-dev \           
          zlib1g-dev \            
          libfreetype6-dev \      
          libxml2-dev \           
          libxslt1-dev 
          # Add any other dependencies your project might need for compilation
          # For example, if you use `pycurl`: libcurl4-openssl-dev
          # If you use `pylibmc`: libmemcached-dev
          # Add more as per your `requirements.txt` and error logs
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
